name: Ledger Accountable Test Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.7

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: rake test
